### PR TITLE
fix Arc, Rc and add Range impls

### PR DESCRIPTION
**Pull request by s3bk**

### CODE REVIEW

**Comment by s3bk** [comment]
I had to made some changes and would like to ask if they can be merged and new version be released.
(It is used in the pdf crate, and I want to release a new version for it...)

**Review by marc-casperlabs — COMMENTED** [review]
The `? Sized` bounds are welcome, but a range is just a set of indices - thus it has no heap allocations at all - or am I thoroughly confused?

So overal, I'd expect `Range<T>` to always have a heap-size of `0`.

If I'm wrong, please add a test that proves me wrong (we'd need one anyway :)).

**Comment by s3bk** [comment]
I can't write code this weak, but i am 99% certain that Range<T> is equivalent of a (T, T) tuple.

**Comment by marc-casperlabs** [comment]
I get it now, it did not occur to me to use heap-allocating types as range bounds before, but I'm sure there's a legit reason somewhere :)

**Review by marc-casperlabs — APPROVED** [review]
Looks good to me.

**Comment by s3bk** [comment]
I am sure some use could be found...

Thanks!

**Pull request merged**
